apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: tasmidur/my-app-image:master-ddb0bb449bf5e6a82f89b1eef9c5f9d1dcbcefcb
          imagePullPolicy: Always
          ports:
            - containerPort: 8019
