apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: tasmidur/my-app-image:master-ff9f676bf02f98754f09ae727a66ad17da2ad432
          imagePullPolicy: Always
          ports:
            - containerPort: 8019
