# Service YAML
apiVersion: v1 
kind: Service
metadata:
  name: my-service
  namespace: my-deployment
spec:
  selector:
    app: my-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8019
  type: NodePort
